- name: install redis
  apt: pkg=redis-server state=installed update-cache=yes
  tags:
    - redis

- name: configure redis
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  notify: restart redis
  tags:
    - redis
