---
- name: restart nginx
  service: name=nginx state=restarted
  sudo_user: root

- name: reload nginx
  service: name=nginx state=reloaded
  sudo_user: root

- name: restart web frontend
  action: service name={{project_name}}_gunicorn state=restarted
  sudo_user: root