---
elasticsearch:
  url: 'http://download.elasticsearch.org/elasticsearch/elasticsearch'
  deb:
    package: 'elasticsearch-1.0.1.deb'
    service: 'elasticsearch'
    dependencies:
      - 'openjdk-7-jre'
      - 'openjdk-7-jdk'
  plugin: '/usr/share/elasticsearch/bin/plugin'
  config: '/etc/elasticsearch/elasticsearch.yml'

  tmp: '/tmp'

# paramedic:
#  index: '/usr/share/elasticsearch/plugins/paramedic/_site/index.html'
#  name: 'karmi/elasticsearch-paramedic'