---
# Install Elasticsearch dependencies
#- name: "Install Elasticsearch dependencies"
#  action: ${ansible_pkg_mgr} pkg={{ item }} state=installed update-cache=yes
#  with_items: elasticsearch.deb.dependencies

# Fetch Elasticsearch Debian package
- name: "Fetch Elasticsearch"
  action: get_url url={{ elasticsearch.url }}/{{ elasticsearch.deb.package }} dest={{ elasticsearch.tmp }} thirsty=yes mode=0440
  register: elasticsearch_deb

# Install Elasticsearch
- name: "Install Elasticsearch package"
  action: shell dpkg -i -E --force-confnew {{ elasticsearch.tmp }}/{{ elasticsearch.deb.package }} 2>&1 | grep skipping | wc -l
  when: elasticsearch_deb.changed 

# Ensure Elasticsearch is running
- name: "Ensure Elasticsearch is running"
  sudo: yes
  service: name={{ elasticsearch.deb.service }} state=started