project_name: caliopen
project_root: /var/projects/caliopen
project_basedir: caliopen.web
project_base_repo: https://github.com/CaliOpen
project_repositories:
  - caliopen.config
  - caliopen.core
  - caliopen.messaging
  - caliopen.smtp
  - caliopen.storage
  - caliopen.api
  - caliopen.ng
  - caliopen.web
system_packages:
  - sudo
  - build-essential
  - git
  - nginx
  - python-dev
  - python-setuptools
  - python-pycurl
  - curl
  - libffi-dev
  - redis-server
python_packages:
  - pip
  - virtualenv
nodejs_packages:
  - nodejs
  - nodejs-legacy
nodejs_modules:
  - bower
  - grunt
  - grunt-cli
initfiles:
  - gunicorn