
---

- name: Create the project directory.
  file: state=directory path={{project_root}}

- name: Create user.
  user: home="{{project_root}}/home/" name="{{project_name}}" state=present shell=/bin/bash

- name: Update the project directory.
  file: group="{{project_name}}" owner="{{project_user}}" mode=755 state=directory path="{{project_root}}"

- name: Create the code directory.
  file: group="{{project_name}}" owner="{{project_user}}" mode=755 state=directory path="{{project_root}}/code/"

- name: Install required system packages.
  apt: pkg="{{item}}" state=installed update-cache=yes
  with_items: "{{system_packages}}"

- name: add wheezy backport to apt source (for nodejs)
  apt_repository: repo="deb http://ftp.us.debian.org/debian wheezy-backports main" state=present

- name: Install required Python packages.
  easy_install: name="{{item}}"
  with_items: "{{python_packages}}"

- name: install nodejs
  apt: pkg="{{item}}" state=installed update-cache=yes
  with_items: "{{nodejs_packages}}"

#  DO NOT WORK, maybe a stdin/out problem on curl
- name: download npm install
  command: curl "https://www.npmjs.com/install.sh" -o /tmp/install.sh
  tags:
    - npm

- name: install npm
  command: sh /tmp/install.sh
  tags:
    - npm

- name: Pull sources from the repository.
  git: repo={{ project_base_repo }}/caliopen-dev.git dest={{ project_root }}/bin
  sudo: true
  sudo_user: "{{ project_user }}"

- name: Install CaliOpen
  command: "{{ project_root }}/bin/install"
  sudo: true
  sudo_user: "{{ project_user }}"
